# Generated by Django 4.2.4 on 2024-01-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_participants_chat_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='no name'),
            preserve_default=False,
        ),
    ]
