# Generated by Django 4.2.4 on 2023-09-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_label', '0002_alter_post_table'),
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(related_name='liked_by', to='core_label.post'),
        ),
    ]
