# Generated by Django 4.2.4 on 2023-11-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_label', '0001_initial'),
        ('core_user', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments_liked',
            field=models.ManyToManyField(related_name='comment_liked_by', to='comment_label.comment'),
        ),
    ]
